apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wiz-cluster-plz-work-this-time
  region: us-east-1

vpc:
  id: "vpc-ff5b1b85" # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16" # (optional, must match CIDR used by the given VPC)
  subnets: # must provide 'private' and/or 'public' subnets by availability zone
    private:
      us-east-1a:
        id: "subnet-05b4848fa221e0d86"
        cidr: "172.31.121.0/24" # must match CIDR range of subnet

      us-east-1b:
        id: "subnet-0e181cebc851c5f86"
        cidr: "172.31.122.0/24" # must match CIDR range of subnet
  
nodeGroups:
  - name: WizNodeGroup
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true