apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-admin
  namespace: wiz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: wiz-admin
  namespace: wiz
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: django-pod
#   namespace: wiz
# spec:
#   serviceAccountName: wiz-admin
#   containers:
#   - name: wiz-app-container
#     image: public.ecr.aws/w6o8q6l8/wiztestimagefinal:latest
#     ports:
#     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: wiz
spec:
  selector:
    app: wiz
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: django
#   namespace: wiz
# subsets:
#   - addresses:
#       - ip: 172.31.122.126
#     ports:
#       - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: wiz
spec:
  selector:
    matchLabels:
      app: wiz
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: wiz
    spec:
      serviceAccountName: wiz-admin
      containers:
        - name: wiz-app-container
          image: public.ecr.aws/w6o8q6l8/wiztestimagefinal:latest
          ports:
          - containerPort: 80